site_name: DungeonDocs
site_description: Gatherâ€™s searchable rules reference
site_url: https://dungeondocs.pages.dev

theme:
  name: material
  logo: images/DungeonDocs-logo.png
  favicon: images/DungeonDocs-favicon.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

plugins:
  - exclude:
      glob:
        - "dnd5e/**"
  - og_meta_plugin
  - search:
      separator: '[\s\-]+'

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Backgrounds:
    - All Backgrounds: dnd2024/backgrounds/index.md
    - Aberrant Heir: dnd2024/backgrounds/aberrant-heir.md
    - Acolyte: dnd2024/backgrounds/acolyte.md
    - Archaeologist: dnd2024/backgrounds/archaeologist.md
    - Artisan: dnd2024/backgrounds/artisan.md
    - Carouser: dnd2024/backgrounds/carouser.md
    - Charlatan: dnd2024/backgrounds/charlatan.md
    - Chondathan Freebooter: dnd2024/backgrounds/chondathan-freebooter.md
    - Criminal: dnd2024/backgrounds/criminal.md
    - Dead Magic Dweller: dnd2024/backgrounds/dead-magic-dweller.md
    - Dragon Cultist: dnd2024/backgrounds/dragon-cultist.md
    - Emerald Enclave Caretaker: dnd2024/backgrounds/emerald-enclave-caretaker.md
    - Entertainer: dnd2024/backgrounds/entertainer.md
    - Farmer: dnd2024/backgrounds/farmer.md
    - Flaming Fist Mercenary: dnd2024/backgrounds/flaming-fist-mercenary.md
    - Genie Touched: dnd2024/backgrounds/genie-touched.md
    - Guard: dnd2024/backgrounds/guard.md
    - Guide: dnd2024/backgrounds/guide.md
    - Harper: dnd2024/backgrounds/harper.md
    - Hermit: dnd2024/backgrounds/hermit.md
    - House Agent: dnd2024/backgrounds/house-agent.md
    - House Cannith Heir: dnd2024/backgrounds/house-cannith-heir.md
    - House Deneith Heir: dnd2024/backgrounds/house-deneith-heir.md
    - House Ghallanda Heir: dnd2024/backgrounds/house-ghallanda-heir.md
    - House Jorasco Heir: dnd2024/backgrounds/house-jorasco-heir.md
    - House Kundarak Heir: dnd2024/backgrounds/house-kundarak-heir.md
    - House Lyrandar Heir: dnd2024/backgrounds/house-lyrandar-heir.md
    - House Medani Heir: dnd2024/backgrounds/house-medani-heir.md
    - House Orien Heir: dnd2024/backgrounds/house-orien-heir.md
    - House Phiarlan Heir: dnd2024/backgrounds/house-phiarlan-heir.md
    - House Sivis Heir: dnd2024/backgrounds/house-sivis-heir.md
    - House Tharashk Heir: dnd2024/backgrounds/house-tharashk-heir.md
    - House Thuranni Heir: dnd2024/backgrounds/house-thuranni-heir.md
    - House Vadalis Heir: dnd2024/backgrounds/house-vadalis-heir.md
    - Ice Fisher: dnd2024/backgrounds/ice-fisher.md
    - Inquisitive: dnd2024/backgrounds/inquisitive.md
    - Knight of the Gauntlet: dnd2024/backgrounds/knight-of-the-gauntlet.md
    - Lords Alliance Vassal: dnd2024/backgrounds/lords-alliance-vassal.md
    - Lorwyn Expert: dnd2024/backgrounds/lorwyn-expert.md
    - Merchant: dnd2024/backgrounds/merchant.md
    - Moonwell Pilgrim: dnd2024/backgrounds/moonwell-pilgrim.md
    - Mulhorandi Tomb Raider: dnd2024/backgrounds/mulhorandi-tomb-raider.md
    - Mythalkeeper: dnd2024/backgrounds/mythalkeeper.md
    - Noble: dnd2024/backgrounds/noble.md
    - Purple Dragon Squire: dnd2024/backgrounds/purple-dragon-squire.md
    - Rashemi Wanderer: dnd2024/backgrounds/rashemi-wanderer.md
    - Sage: dnd2024/backgrounds/sage.md
    - Sailor: dnd2024/backgrounds/sailor.md
    - Scribe: dnd2024/backgrounds/scribe.md
    - Shadowmasters Exile: dnd2024/backgrounds/shadowmasters-exile.md
    - Shadowmoor Expert: dnd2024/backgrounds/shadowmoor-expert.md
    - Soldier: dnd2024/backgrounds/soldier.md
    - Spellfire Initiate: dnd2024/backgrounds/spellfire-initiate.md
    - Vampire Devotee: dnd2024/backgrounds/vampire-devotee.md
    - Vampire Survivor: dnd2024/backgrounds/vampire-survivor.md
    - Wayfarer: dnd2024/backgrounds/wayfarer.md
    - Zhentarim Mercenary: dnd2024/backgrounds/zhentarim-mercenary.md
  - Classes:
    - Artificer:
      - dnd2024/classes/artificer/index.md
      - Alchemist: dnd2024/classes/artificer/alchemist.md
      - Armorer: dnd2024/classes/artificer/armorer.md
      - Artillerist: dnd2024/classes/artificer/artillerist.md
      - Battle Smith: dnd2024/classes/artificer/battle-smith.md
      - Cartographer: dnd2024/classes/artificer/cartographer.md
      - Spell List: dnd2024/classes/artificer/spell-list.md
    - Barbarian:
      - dnd2024/classes/barbarian/index.md
      - Path of the Berserker: dnd2024/classes/barbarian/path-of-the-berserker.md
      - Path of the Wild Heart: dnd2024/classes/barbarian/path-of-the-wild-heart.md
      - Path of the World Tree: dnd2024/classes/barbarian/path-of-the-world-tree.md
      - Path of the Zealot: dnd2024/classes/barbarian/path-of-the-zealot.md
    - Bard:
      - dnd2024/classes/bard/index.md
      - College of Dance: dnd2024/classes/bard/college-of-dance.md
      - College of Glamour: dnd2024/classes/bard/college-of-glamour.md
      - College of Lore: dnd2024/classes/bard/college-of-lore.md
      - College of the Moon: dnd2024/classes/bard/college-of-the-moon.md
      - College of Valor: dnd2024/classes/bard/college-of-valor.md
      - Spell List: dnd2024/classes/bard/spell-list.md
    - Cleric:
      - dnd2024/classes/cleric/index.md
      - Knowledge Domain: dnd2024/classes/cleric/knowledge-domain.md
      - Life Domain: dnd2024/classes/cleric/life-domain.md
      - Light Domain: dnd2024/classes/cleric/light-domain.md
      - Trickery Domain: dnd2024/classes/cleric/trickery-domain.md
      - War Domain: dnd2024/classes/cleric/war-domain.md
      - Spell List: dnd2024/classes/cleric/spell-list.md
    - Druid:
      - dnd2024/classes/druid/index.md
      - Circle of the Land: dnd2024/classes/druid/circle-of-the-land.md
      - Circle of the Moon: dnd2024/classes/druid/circle-of-the-moon.md
      - Circle of the Sea: dnd2024/classes/druid/circle-of-the-sea.md
      - Circle of the Stars: dnd2024/classes/druid/circle-of-the-stars.md
      - Spell List: dnd2024/classes/druid/spell-list.md
    - Fighter:
      - dnd2024/classes/fighter/index.md
      - Banneret: dnd2024/classes/fighter/banneret.md
      - Battle Master: dnd2024/classes/fighter/battle-master.md
      - Champion: dnd2024/classes/fighter/champion.md
      - Eldritch Knight: dnd2024/classes/fighter/eldritch-knight.md
      - Psi Warrior: dnd2024/classes/fighter/psi-warrior.md
    - Monk:
      - dnd2024/classes/monk/index.md
      - Warrior of Mercy: dnd2024/classes/monk/warrior-of-mercy.md
      - Warrior of Shadow: dnd2024/classes/monk/warrior-of-shadow.md
      - Warrior of the Elements: dnd2024/classes/monk/warrior-of-the-elements.md
      - Warrior of the Open Hand: dnd2024/classes/monk/warrior-of-the-open-hand.md
    - Paladin:
      - dnd2024/classes/paladin/index.md
      - Oath of Devotion: dnd2024/classes/paladin/oath-of-devotion.md
      - Oath of Glory: dnd2024/classes/paladin/oath-of-glory.md
      - Oath of the Ancients: dnd2024/classes/paladin/oath-of-the-ancients.md
      - Oath of the Noble Genies: dnd2024/classes/paladin/oath-of-the-noble-genies.md
      - Oath of Vengeance: dnd2024/classes/paladin/oath-of-vengeance.md
      - Spell List: dnd2024/classes/paladin/spell-list.md
    - Ranger:
      - dnd2024/classes/ranger/index.md
      - Beast Master: dnd2024/classes/ranger/beast-master.md
      - Fey Wanderer: dnd2024/classes/ranger/fey-wanderer.md
      - Gloom Stalker: dnd2024/classes/ranger/gloom-stalker.md
      - Hunter: dnd2024/classes/ranger/hunter.md
      - Winter Walker: dnd2024/classes/ranger/winter-walker.md
      - Spell List: dnd2024/classes/ranger/spell-list.md
    - Rogue:
      - dnd2024/classes/rogue/index.md
      - Arcane Trickster: dnd2024/classes/rogue/arcane-trickster.md
      - Assassin: dnd2024/classes/rogue/assassin.md
      - Scion of the Three: dnd2024/classes/rogue/scion-of-the-three.md
      - Soulknife: dnd2024/classes/rogue/soulknife.md
      - Thief: dnd2024/classes/rogue/thief.md
    - Sorcerer:
      - dnd2024/classes/sorcerer/index.md
      - Aberrant Sorcery: dnd2024/classes/sorcerer/aberrant-sorcery.md
      - Clockwork Sorcery: dnd2024/classes/sorcerer/clockwork-sorcery.md
      - Draconic Sorcery: dnd2024/classes/sorcerer/draconic-sorcery.md
      - Metamagic: dnd2024/classes/sorcerer/metamagic.md
      - Spellfire Sorcery: dnd2024/classes/sorcerer/spellfire-sorcery.md
      - Wild Magic Sorcery: dnd2024/classes/sorcerer/wild-magic-sorcery.md
      - Spell List: dnd2024/classes/sorcerer/spell-list.md
    - Warlock:
      - dnd2024/classes/warlock/index.md
      - Archfey Patron: dnd2024/classes/warlock/archfey-patron.md
      - Celestial Patron: dnd2024/classes/warlock/celestial-patron.md
      - Fiend Patron: dnd2024/classes/warlock/fiend-patron.md
      - Great Old One Patron: dnd2024/classes/warlock/great-old-one-patron.md
      - Eldritch Invocation: dnd2024/classes/warlock/eldritch-invocation.md
      - Spell List: dnd2024/classes/warlock/spell-list.md
    - Wizard:
      - dnd2024/classes/wizard/index.md
      - Abjurer: dnd2024/classes/wizard/abjurer.md
      - Bladesinger: dnd2024/classes/wizard/bladesinger.md
      - Diviner: dnd2024/classes/wizard/diviner.md
      - Evoker: dnd2024/classes/wizard/evoker.md
      - Illusionist: dnd2024/classes/wizard/illusionist.md
      - Spell List: dnd2024/classes/wizard/spell-list.md
    - Multiclassing: dnd2024/classes/multiclassing.md
  - Feats: dnd2024/feats/index.md
  - Species:
    - All Species: dnd2024/species/all.md
    - Aasimar: dnd2024/species/aasimar.md
    - Boggart: dnd2024/species/boggart.md
    - Changeling: dnd2024/species/changeling.md
    - Dhampir: dnd2024/species/dhampir.md
    - Dragonborn: dnd2024/species/dragonborn.md
    - Dwarf: dnd2024/species/dwarf.md
    - Elf: dnd2024/species/elf.md
    - Faerie: dnd2024/species/faerie.md
    - Flamekin: dnd2024/species/flamekin.md
    - Gnome: dnd2024/species/gnome.md
    - Goliath: dnd2024/species/goliath.md
    - Halfling: dnd2024/species/halfling.md
    - Human: dnd2024/species/human.md
    - Kalashtar: dnd2024/species/kalashtar.md
    - Khoravar: dnd2024/species/khoravar.md
    - Lorwyn Changeling: dnd2024/species/lorwyn-changeling.md
    - Orc: dnd2024/species/orc.md
    - Rimekin: dnd2024/species/rimekin.md
    - Shifter: dnd2024/species/shifter.md
    - Tiefling: dnd2024/species/tiefling.md
    - Warforged: dnd2024/species/warforged.md
